### ISSUE TITLE
Docs and examples are necessary

### ISSUE THREAD

**Issue by matiasbenedetto** [bbc/react-lrud#1]
Docs and examples will be very useful to use the ibrary. :)
Thanks!

**Comment by jfrux** [comment]
I agree, I'm having trouble understanding how this is supposed to work.
I'm using this as a way to understand the lrud library itself.

Does this handle moving the focus and all of that or is that a different library?

**Comment by thomascgray** [comment]
Apologies for the late reply guys!

React LRUD was designed as a tool for use in conjunction with [LRUD](https://github.com/bbc/lrud).

The typical work flow was designed as;

- you create an LRUD instance
- you tag up your react components with specific tags, and place them all inside a special provider component
- you give the provider your LRUD instance

and your LRUD instance is the populated with nodes representing your React components.

### What's changing?

However, current thinking is that we actually want to *step away* from using React LRUD, and instead accept that an LRUD navigation tree and your visual components are *entirely distinct*. 

The navigation tree and the visual elements are, and *should be*, entirely distinct from each other. React LRUD, while in a sense helping to generate the navigation tree, is actually tightly coupling these processes together.

More writing will be done on this in the near future, especially considering we're about to do a major new release of LRUD, in [this PR](https://github.com/bbc/lrud/pull/6), but for now, we have no plans for long term maintenance of React LRUD.

**Comment by thomascgray** [comment]
@jfrux 

> Does this handle moving the focus and all of that or is that a different library?

[LRUD](https://github.com/bbc/lrud) is the library that actually holds a navigation tree and handles events to represent changes in the state of that tree.
