### ISSUE TITLE
React-LRUD v3 compatibility?

### ISSUE THREAD

**Issue by perqa** [bbc/react-lrud#25]
I would like to use LRUD v3 in a React application. Just wondering what the timeframe might be until we see an upgrade of React-LRUD for use with LRUD V3?

**Comment by kukulaka** [comment]
Hi @perqa , sorry it's taken a little while for anyone to get back to you. LRUD has recently been moved to [maintenance mode](https://github.com/bbc/lrud#nut_and_bolt-maintenance-mode-nut_and_bolt), so there are no plans to upgrade react-lrud to use V3.  We are in the process of deprecating  react-lrud. 

BBC have recently made [LRUD Spatial](https://github.com/bbc/lrud-spatial) open source, and we recommend using this library going forward.
