### ISSUE TITLE
Navigation doesn't happen

### ISSUE THREAD

**Issue by Jazzie-z** [bbc/react-lrud#5]
I created a simple component just like in the example but the focus and navigation doesn't seem to work. Could you give me an example on how to create a simple grid.

**Comment by thomascgray** [comment]
Apologies for the late reply.

Please see my response on https://github.com/bbc/react-lrud/issues/1 for more details into whats happening, but tl;dr we have no long term plans to support React LRUD.

If you want more documentation on some examples, we're about to release a major re-write of the base LRUD library, which now includes some recipe documentation.

If you want to take a look at that before it gets merged, you can see it [here](https://github.com/bbc/lrud/pull/6/files#diff-f2d1eb072b7cb530c555baf35e664b9c)
